# Generated by Django 3.0.3 on 2020-03-10 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20200310_0133'),
        ('pedidos', '0002_auto_20200310_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Producto'),
        ),
    ]
