# Generated by Django 3.0.7 on 2021-03-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_equipo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('descripcion', models.CharField(max_length=80, unique=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], default=('ACTIVO', 'ACTIVO'), max_length=40)),
                ('modelo', models.CharField(max_length=80, unique=True)),
                ('costo', models.IntegerField()),
                ('codigo_elaboracion', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
    ]
