# Generated by Django 3.0.3 on 2020-03-11 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo_producto', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('volumen', models.FloatField(blank=True)),
                ('color', models.CharField(blank=True, max_length=10)),
                ('precio', models.FloatField(blank=True)),
                ('cantidad_neto', models.FloatField(blank=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
