# Generated by Django 3.0.3 on 2020-03-10 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20200309_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad_neto',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='volumen',
            field=models.FloatField(blank=True),
        ),
    ]
