# Generated by Django 3.0.7 on 2021-03-04 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, null=True)),
                ('nro_factura', models.CharField(max_length=20, unique=True)),
                ('fecha_pago', models.DateField()),
                ('monto_total', models.IntegerField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('FINALIZADO', 'Finalizado')], default=('PENDIENTE', 'Pendiente'), max_length=40)),
                ('metodo_pago', models.CharField(choices=[('TARJETA CREDITO/DEBITO', 'Tarjeta Credito/Debito'), ('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA BANCARIA', 'Transferencia Bancaria'), ('CHEQUE', 'Cheque')], default=('TARJETA CREDITO/DEBITO', 'Tarjeta Credito/Debito'), max_length=40)),
                ('tipo_pago', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Credito')], default=('CONTADO', 'Contado'), max_length=40)),
                ('cantidad_cuotas', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='PagoCuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(null=True)),
                ('fecha_vencimiento', models.DateField()),
                ('monto_cuota', models.IntegerField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('PAGADA', 'PAGADA')], default=('PENDIENTE', 'PENDIENTE'), max_length=40)),
                ('id_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagos.Pago')),
            ],
            options={
                'verbose_name': 'PagoCuota',
                'verbose_name_plural': 'Pagos Cuotas',
            },
        ),
    ]
